CvGenerator/Models/WorkExperience.cs
using System.ComponentModel.DataAnnotations;

namespace CvGenerator.Models
{
    public class WorkExperience
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Company { get; set; }
        [Required]
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        [Required]
        public string Responsibilities { get; set; }
    }
}

CvGenerator/Models/WorkExperiences.cs
using System.ComponentModel.DataAnnotations;

namespace CvGenerator.Models
{
    public class WorkExperiences
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Company { get; set; }
        [Required]
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        [Required]
        public string Responsibilities { get; set; }
    }
}

CvGenerator/Controllers/WorkExperienceController.cs
using CvGenerator.Data;
using CvGenerator.Models;
using Microsoft.AspNetCore.Mvc;

namespace CvGenerator.Controllers
{
    public class WorkExperienceController : Controller
    {
            private readonly ApplicationDbContext _db;

            public WorkExperienceController(ApplicationDbContext db)
            {
                _db = db;
            }
            public IActionResult Index()
            {
            ViewData["Title"] = "Work Experience";
            IEnumerable<WorkExperiences> objExpList = _db.WorkExperiences;
                return View(objExpList);
            }
            public IActionResult Create()
            {

                return View();
            }
            public IActionResult Edit(int? id)
            {
                if (id == null || id == 0)
                {
                    return NotFound();
                }
                var expFromDb = _db.WorkExperiences.Find(id);

                if (expFromDb == null)
                {
                    return NotFound();
                }
                return View(expFromDb);
            }

            [HttpPost]
            [ValidateAntiForgeryToken]
            public IActionResult Create(WorkExperiences obj)
            {
                if (ModelState.IsValid)
                {
                    _db.WorkExperiences.Add(obj);
                    _db.SaveChanges();
                    TempData["success"] = "Work Experience created successfully";
                    return RedirectToAction("Index");
                }
                return View(obj);
            }

            [HttpPost]
            [ValidateAntiForgeryToken]
            public IActionResult Edit(WorkExperiences obj)
            {
                if (ModelState.IsValid)
                {
                    _db.WorkExperiences.Update(obj);
                    _db.SaveChanges();
                    TempData["success"] = "Work Ecperience updated successfully";
                    return RedirectToAction("Index");
                }
                return View(obj);
            }
            public IActionResult Delete(int? id)
            {
                if (id == null || id == 0)
                {
                    return NotFound();
                }
                var expFromDb = _db.WorkExperiences.Find(id);

                if (expFromDb == null)
                {
                    return NotFound();
                }

                return View(expFromDb);
            }

            //POST
            [HttpPost, ActionName("Delete")]
            [ValidateAntiForgeryToken]
            public IActionResult DeletePOST(int? id)
            {
                var obj = _db.WorkExperiences.Find(id);
                if (obj == null)
                {
                    return NotFound();
                }

                _db.WorkExperiences.Remove(obj);
                _db.SaveChanges();
                TempData["success"] = "Work Experience deleted successfully";
                return RedirectToAction("Index");

            }
        }
    }

CvGenerator/Views/WorkExperience/Create.cshtml
@model WorkExperiences

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row-pb-2">
            <h2 class="text-primary">Create new work experience</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Title">Title Name</label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Company">Company Name</label>
            <input asp-for="Company" class="form-control" />
            <span asp-validation-for="Company" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="StartDate">Start Date</label>
            <input asp-for="StartDate" class="form-control" type="date" />
            <span asp-validation-for="StartDate" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="EndDate">End Date</label>
            <input asp-for="EndDate" class="form-control" type="date" />

        </div>
        <div class="mb-3">
            <label asp-for="Responsibilities">Responsibilities</label>
            <input asp-for="Responsibilities" class="form-control" />
            <span asp-validation-for="Responsibilities" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="WorkExperiences" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to List
        </a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

CvGenerator/Views/WorkExperience/Delete.cshtml
@model WorkExperiences

<form method="post" asp-action="Delete">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Work Experience</h2>
            <hr />
        </div>
        @*<div asp-validation-summary="All"></div>*@
        <div class="mb-3">
            <label asp-for="Title">Title Name</label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Company">Company Name</label>
            <input asp-for="Company" class="form-control" />
            <span asp-validation-for="Company" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="StartDate">Start Date</label>
            <input asp-for="StartDate" class="form-control" type="date" />
            <span asp-validation-for="StartDate" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="EndDate">End Date</label>
            <input asp-for="EndDate" class="form-control" type="date" />
            <span asp-validation-for="EndDate" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Responsibilities">Responsibilities</label>
            <input asp-for="Responsibilities" class="form-control" />
            <span asp-validation-for="Responsibilities" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
        <a asp-controller="WorkExperience" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to List
        </a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

CvGenerator/Views/WorkExperience/Edit.cshtml
@model WorkExperiences
<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row-pb-2">
            <h2 class="text-primary">Edit Work Experience</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Title">Title Name</label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Company">Company Name</label>
            <input asp-for="Company" class="form-control" />
            <span asp-validation-for="Company" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="StartDate">Start Date</label>
            <input asp-for="StartDate" class="form-control" type="date" />
            <span asp-validation-for="StartDate" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="EndDate">End Date</label>
            <input asp-for="EndDate" class="form-control" type="date" />
            <span asp-validation-for="EndDate" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Responsibilities">Responsibilities</label>
            <input asp-for="Responsibilities" class="form-control" />
            <span asp-validation-for="Responsibilities" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
        <a asp-controller="WorkExperience" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to List
        </a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

CvGenerator/Views/WorkExperience/Index.cshtml
@model IEnumerable<WorkExperiences>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Work Experience List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="WorkExperience" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Create new work experience
            </a>

        </div>
    </div>

    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Title Name
                </th>
                <th>
                    Company Name
                </th>
                <th>
                    Start Date
                </th>
                <th>
                    End Date
                </th>
                <th>
                    Responsibilities
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td width="17%">
                        @obj.Title
                    </td>
                    <td width="17%">
                        @obj.Company
                    </td>
                    <td width="17%">
                        @obj.StartDate.ToString("yyyy-MM-dd")
                    </td>
                    <td width="17%">
                        @obj.EndDate.ToString("yyyy-MM-dd")
                    </td>
                    <td width="17%">
                        @obj.Responsibilities
                    </td>
                    
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="WorkExperience" asp-action="Edit" asp-route-id="@obj.Id"
                               class="btn btn-primary mx-2"> <i class="bi bi-pencil-square"></i> Edit</a>
                            <a asp-controller="WorkExperience" asp-action="Delete" asp-route-id="@obj.Id"
                               class="btn btn-danger mx-2"> <i class="bi bi-trash-fill"></i> Delete</a>
                        </div>
                    </td>

                </tr>
            }
        </tbody>
    </table>
</div>