CvGenerator/Models/Description.cs
using System.ComponentModel.DataAnnotations;

namespace CvGenerator.Models
{
    public class Description
    {
        [Key]
        public int DescriptionId{get; set;}
        public string Des { get; set;}
    }
}

CvGenerator/Models/Descriptions.cs
using System.ComponentModel.DataAnnotations;

namespace CvGenerator.Models
{
    public class Descriptions
    {
        [Key]
        public int Id{get; set;}
        public string Des { get; set;}
    }
}

CvGenerator/Controllers/DescriptionController.cs
using CvGenerator.Data;
using CvGenerator.Models;
using Microsoft.AspNetCore.Mvc;

namespace CvGenerator.Controllers
{
    public class DescriptionController : Controller
    {
        private readonly ApplicationDbContext _db;

        public DescriptionController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            ViewData["Title"] = "About me";
            IEnumerable<Descriptions> objDesList = _db.Descriptions;
            return View(objDesList);
        }
        public IActionResult Create()
        {
            if (_db.Descriptions.Any())
            {
                ViewBag.DisableCreate = true;
            }
            else
            {
                ViewBag.DisableCreate = false;
            }
            return View();
        }
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var desFromDb = _db.Descriptions.Find(id);

            if (desFromDb == null)
            {
                return NotFound();
            }
            return View(desFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Descriptions obj)
        {
            if (ModelState.IsValid)
            {
                _db.Descriptions.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Description created successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Descriptions obj)
        {
            if (ModelState.IsValid)
            {
                _db.Descriptions.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Description updated successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var desFromDb = _db.Descriptions.Find(id);

            if (desFromDb == null)
            {
                return NotFound();
            }

            return View(desFromDb);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _db.Descriptions.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            _db.Descriptions.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Description deleted successfully";
            return RedirectToAction("Index");

        }
    }
}

CvGenerator/Views/Description/Create.cshtml
@model Descriptions
@{
    bool disableCreate = ViewBag.DisableCreate ?? false;
}

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row-pb-2">
            <h2 class="text-primary">Create new Description</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Des">Description</label>
            <input asp-for="Des" class="form-control" />
            <span asp-validation-for="Des" class="text-danger"></span>
        </div>
  

        <button type="submit" class="btn btn-primary" style="width:150px" @if (disableCreate) { <text>disabled</text> }>Create</button>
        <a asp-controller="Description" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to List
        </a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

CvGenerator/Views/Description/Delete.cshtml
@model Descriptions

<form method="post" asp-action="Delete">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Description</h2>
            <hr />
        </div>
        @*<div asp-validation-summary="All"></div>*@
        <div class="mb-3">
            <label asp-for="Des">Description</label>
            <input asp-for="Des" class="form-control" />
            <span asp-validation-for="Des" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
        <a asp-controller="Description" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to List
        </a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

CvGenerator/Views/Description/Edit.cshtml
@model Descriptions
<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row-pb-2">
            <h2 class="text-primary">Edit Description</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Des">Description</label>
            <input asp-for="Des" class="form-control" />
            <span asp-validation-for="Des" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
        <a asp-controller="Description" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to List
        </a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

CvGenerator/Views/Description/Index.cshtml
@model IEnumerable<Descriptions>
@{
    bool disableCreate = Model.Count() >= 1;
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Description</h2>
        </div>
        <div class="col-6 text-end">
            @if (disableCreate)
            {
                <button class="btn btn-primary" disabled>
                    <i class="bi bi-plus-circle"></i> &nbsp; Create description
                </button>
            }
            else
            {
                <a asp-controller="Description" asp-action="Create" class="btn btn-primary">
                    <i class="bi bi-plus-circle"></i> &nbsp; Create description
                </a>
            }
        </div>
    </div>

    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Description
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td width="84%">
                        @obj.Des
                    </td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Description" asp-action="Edit" asp-route-id="@obj.Id"
                               class="btn btn-primary mx-2"> <i class="bi bi-pencil-square"></i> Edit</a>
                            <a asp-controller="Description" asp-action="Delete" asp-route-id="@obj.Id"
                               class="btn btn-danger mx-2"> <i class="bi bi-trash-fill"></i> Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>