CvGenerator/Controllers/AllController.cs
using CvGenerator.Data;
using CvGenerator.Helpers;
using CvGenerator.Models;
using CvGenerator.Models.Session;
using CvGenerator.Repositories;
using CvGenerator.Repository;
using CvGenerator.Repository.CertificationAndTraining;
using CvGenerator.Repository.Description;
using CvGenerator.Repository.References;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Reporting.NETCore;
using Microsoft.ReportingServices.ReportProcessing.ReportObjectModel;
using Newtonsoft.Json;
using System.Drawing.Imaging;
using System.Drawing;
using System;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.ReportingServices.Interfaces;

namespace CvGenerator.Controllers
{
    public class AllController : Controller
    {
        private readonly ISkillRepository _skillsRepository;
        private readonly IUserRepository _userRepository;
        private readonly IEducationRepository _educationRepository;
        private readonly IDescriptionRepository _descriptionRepository;
        private readonly IWorkExperienceRepository _workExperienceRepository;
        private readonly ICertificationAndTrainingRepository _certificationAndTrainingRepository;
        private readonly IReferenceRepository _referenceRepository;
        private readonly ApplicationDbContext _db;

        public AllController(
            ISkillRepository skillRepository,
            IUserRepository userRepository,
            IEducationRepository educationRepository,
            IDescriptionRepository descriptionRepository,
            IWorkExperienceRepository workExperienceRepository,
            ICertificationAndTrainingRepository certificationAndTrainingRepository,
            IReferenceRepository referenceRepository,
            ApplicationDbContext db)
        {
            _skillsRepository = skillRepository;
            _userRepository = userRepository;
            _educationRepository = educationRepository;
            _descriptionRepository = descriptionRepository;
            _workExperienceRepository = workExperienceRepository;
            _certificationAndTrainingRepository = certificationAndTrainingRepository;
            _referenceRepository = referenceRepository;
            _db = db;
        }

        public IActionResult Index()
        {
     
            var users = _db.Users.ToList();
            var work = _db.WorkExperiences.ToList();
            var cer = _db.CertificationAndTrainings.ToList();
            var skills = _db.Skill.ToList();
            var description = _db.Descriptions.ToList();
            var edu = _db.Educations.ToList();
            var refe = _db.Reference.ToList();

            var viewModel = new All
            {
                Skills = skills,
                User = users,
                Education = edu,
                Description = description,
                CertificationAndTraining = cer,
                References = refe,
                WorkExperience = work,
            };
            return View(viewModel);
        }
   

        [HttpPost]
        public async Task<IActionResult> OpenIndexReport(ReportType type)
        {
            var skill = await _db.Skill.Select(t => new
            {
                Name = t.Name,
                Description = t.Description
            }).ToListAsync();
            var des = await _db.Descriptions.Select(t => new
            {
                Des = t.Des,
            }).ToListAsync();
            var user = await _db.Users.Select(t => new
            {
                FirstName = t.FirstName,
                LastName = t.LastName,
                PhoneNumber = t.PhoneNumber,
                Address = t.Address,
                BirthDate = t.BirthDate,
                Email = t.Email
            }).ToListAsync();
            var cer = await _db.CertificationAndTrainings.Select(t => new
            {
                Name = t.Name,
                Company = t.Company,
                IssueDate = t.IssueDate
            }).ToListAsync();
            var edu = await _db.Educations.Select(t => new
            {
                Name = t.Name,
                Field = t.Field,
                StartDate = t.StartDate,
                EndDate = t.EndDate,
                Grade = t.Grade
            }).ToListAsync();

            var refe = await _db.Reference.Select(t => new
            {
                Name = t.Name,
                Contact = t.Contact,
                Description = t.Description
            }).ToListAsync();

            var exp = await _db.WorkExperiences.Select(t => new
            {
                Title = t.Title,
                Company = t.Company,
                StartDate = t.StartDate,
                EndDate = t.EndDate,
                Responsibilities = t.Responsibilities
            }).ToListAsync();


            RDCLReport rdlc = new RDCLReport();

            List<ReportDataSource> ds = new() { 
                new ReportDataSource("DataSet1", skill),
                new ReportDataSource("DataSet2", des),
                new ReportDataSource("DataSet3", exp),
                new ReportDataSource("DataSet4", refe),
                new ReportDataSource("DataSet5", edu),
                new ReportDataSource("DataSet6", user),
                new ReportDataSource("DataSet7", cer)
            };
            List<ReportParameter> parameters = new(){ };

            var FinalReport = rdlc.GenerateReport("Skills.rdl", type, ds, parameters, "8.27in", "11.67in");
            return type == ReportType.PDF ? File(FinalReport, "application/pdf") : File(FinalReport, "application/ms-excel", "Raporti.xlsx");
        }
    }
}

CvGenerator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CvGenerator</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CvGenerator.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/SideBar.css" />
    <style>
        .nav-pills .nav-link:hover {
            background-color: dimgrey;
        }
    </style>
</head>
<body>
    <header>
        <nav>
            <div class="container-fluid">
                <div class="row flex-nowrap">
                    <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
                        <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                            <a href="@Url.Action("Index", "Home")" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                                <span class="fs-5 d-none d-sm-inline">Menu</span>
                                </a>
                            <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start " id="menu">
                                <li class="nav-item">
                                    <a class="nav-link align-middle px-0 text-white" asp-controller="All" asp-action="Index">
                                        <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">My CV</span>
                                    </a>
                                </li>
                                <li>
                                    <a class="nav-link px-0 align-middle text-white" asp-controller="User" asp-action="Index">
                                        <i class="fs-4 bi-table"></i> <span class="ms-1 d-none d-sm-inline">Personal Informations</span>
                                    </a>
                                </li>
                                <li>
                                    <a class="nav-link px-0 align-middle text-white" asp-controller="Education" asp-action="Index">
                                        <i class="fs-4 bi-people"></i> <span class="ms-1 d-none d-sm-inline">Education</span>
                                    </a>
                                </li>
                                <li>
                                    <a class="nav-link px-0 align-middle text-white" asp-controller="WorkExperience" asp-action="Index">
                                        <i class="fs-4 bi-people"></i> <span class="ms-1 d-none d-sm-inline">Work Experience</span>
                                    </a>
                                </li>
                                <li>
                                    <a class="nav-link px-0 align-middle text-white" asp-controller="Skills" asp-action="Index">
                                        <i class="fs-4 bi-people"></i> <span class="ms-1 d-none d-sm-inline">Skills</span>
                                    </a>
                                </li>
                                <li>
                                    <a class="nav-link px-0 align-middle text-white" asp-controller="CertificationAndTraining" asp-action="Index">
                                        <i class="fs-4 bi-people"></i> <span class="ms-1 d-none d-sm-inline">Certification & Training</span>
                                    </a>
                                </li>
                                <li>
                                    <a class="nav-link px-0 align-middle text-white" asp-controller="References" asp-action="Index">
                                        <i class="fs-4 bi-people"></i> <span class="ms-1 d-none d-sm-inline">Reference</span>
                                    </a>
                                </li>
                                <li>
                                    <a class="nav-link px-0 align-middle text-white" asp-controller="Description" asp-action="Index">
                                        <i class="fs-4 bi-people"></i> <span class="ms-1 d-none d-sm-inline">About Me</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col py-3">
                        <main role="main" class="pb-3">
                            @RenderBody()
                        </main>
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CvGenerator All Rights Reserved
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>