CvGenerator/Models/CertificationAndTraining.cs
using System.ComponentModel.DataAnnotations;

namespace CvGenerator.Models
{
    public class CertificationAndTraining
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        [Required]
        public string Company { get; set; }
        [Required]
        public DateTime IssueDate { get; set; }
    }
}

CvGenerator/Models/CertificationAndTrainings.cs
using System.ComponentModel.DataAnnotations;

namespace CvGenerator.Models
{
    public class CertificationAndTrainings
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        [Required]
        public string Company { get; set; }
        [Required]
        public DateTime IssueDate { get; set; }
    }
}

CvGenerator/Controllers/CertificationAndTrainingController.cs
using CvGenerator.Data;
using CvGenerator.Models;
using Microsoft.AspNetCore.Mvc;

namespace CvGenerator.Controllers
{
    public class CertificationAndTrainingController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CertificationAndTrainingController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            ViewData["Title"] = "Certification and Trainings";

            IEnumerable<CertificationAndTrainings> objCerList = _db.CertificationAndTrainings;
            return View(objCerList);
        }
        public IActionResult Create()
        {

            return View();
        }
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var cerFromDb = _db.CertificationAndTrainings.Find(id);

            if (cerFromDb == null)
            {
                return NotFound();
            }
            return View(cerFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CertificationAndTrainings obj)
        {
            if (ModelState.IsValid)
            {
                _db.CertificationAndTrainings.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Certification and Training created successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CertificationAndTrainings obj)
        {
            if (ModelState.IsValid)
            {
                _db.CertificationAndTrainings.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Certification and Training successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var cerFromDb = _db.CertificationAndTrainings.Find(id);

            if (cerFromDb == null)
            {
                return NotFound();
            }

            return View(cerFromDb);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _db.CertificationAndTrainings.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            _db.CertificationAndTrainings.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Certification and Training deleted successfully";
            return RedirectToAction("Index");

        }
    }
}

CvGenerator/Views/CertificationAndTraining/Create.cshtml
@model CertificationAndTrainings

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row-pb-2">
            <h2 class="text-primary">Create new Certification or Trainig</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name">Certification Name</label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Company">Company</label>
            <input asp-for="Company" class="form-control" />
            <span asp-validation-for="Company" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="IssueDate">Issue Date</label>
            <input asp-for="IssueDate" class="form-control" type="date" />
            <span asp-validation-for="IssueDate" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="CertificationAndTraining" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to List
        </a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

CvGenerator/Views/CertificationAndTraining/Delete.cshtml
@model CertificationAndTrainings

<form method="post" asp-action="Delete">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Certification or Training</h2>
            <hr />
        </div>
        @*<div asp-validation-summary="All"></div>*@
        <div class="mb-3">
            <label asp-for="Name">Certification Name</label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Company">Company</label>
            <input asp-for="Company" class="form-control" />
            <span asp-validation-for="Company" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="IssueDate">Issue Date</label>
            <input asp-for="IssueDate" class="form-control" />
            <span asp-validation-for="IssueDate" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
        <a asp-controller="CertificationAndTraining" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to List
        </a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

CvGenerator/Views/CertificationAndTraining/Edit.cshtml
@model CertificationAndTrainings
<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row-pb-2">
            <h2 class="text-primary">Edit Certification or Training</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name">Certification Name</label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Company">Company</label>
            <input asp-for="Company" class="form-control" />
            <span asp-validation-for="Company" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="IssueDate">Issue Date</label>
            <input asp-for="IssueDate" class="form-control" type="date" />
            <span asp-validation-for="IssueDate" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
        <a asp-controller="CertificationAndTraining" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to List
        </a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

CvGenerator/Views/CertificationAndTraining/Index.cshtml
@model IEnumerable<CertificationAndTrainings>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Certification and Training List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="CertificationAndTraining" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Create new Certification or Training
            </a>

        </div>
    </div>

    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Certification Name
                </th>
                <th>
                    Company Name
                </th>
                <th>
                    Issue Date
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td width="28%">
                        @obj.Name
                    </td>
                    <td width="28%">
                        @obj.Company
                    </td>
                    <td width="28%">
                        @obj.IssueDate.ToString("yyyy-MM-dd")

                    </td>
                    
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="CertificationAndTraining" asp-action="Edit" asp-route-id="@obj.Id"
                               class="btn btn-primary mx-2"> <i class="bi bi-pencil-square"></i> Edit</a>
                            <a asp-controller="CertificationAndTraining" asp-action="Delete" asp-route-id="@obj.Id"
                               class="btn btn-danger mx-2"> <i class="bi bi-trash-fill"></i> Delete</a>
                        </div>
                    </td>

                </tr>
            }
        </tbody>
    </table>
</div>